// Writes the Content-Security-Policy header for nginx, derived from what the build
// actually emitted rather than from a guess. Astro inlines a couple of very small
// scripts (the pre-paint theme script and the toggle), so their exact bytes are
// hashed here; everything else has to come from this origin or not at all.
//
//   node scripts/csp-header.mjs > csp.conf
//
// Run it after every build. If a script changes by one character, the hash changes,
// and a stale header will block it: that is the point of the mechanism.

import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, statSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const dist = join(root, 'dist');

if (!existsSync(dist)) {
  console.error('No dist/ — run npm run build first.');
  process.exit(1);
}

function walk(dir) {
  return readdirSync(dir).flatMap((entry) => {
    const full = join(dir, entry);
    return statSync(full).isDirectory() ? walk(full) : [full];
  });
}

const hashes = new Set();
for (const page of walk(dist).filter((f) => f.endsWith('.html'))) {
  const html = readFileSync(page, 'utf8');
  for (const match of html.matchAll(/<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/g)) {
    hashes.add(`'sha256-${createHash('sha256').update(match[1], 'utf8').digest('base64')}'`);
  }
}

const policy = [
  "default-src 'none'",
  `script-src 'self' ${[...hashes].sort().join(' ')}`.trim(),
  "style-src 'self'",
  "img-src 'self' data:",
  "font-src 'self'",
  "connect-src 'none'",
  "media-src 'none'",
  "base-uri 'none'",
  "form-action 'none'",
  "frame-ancestors 'none'",
].join('; ');

process.stdout.write(
  `# Generated by scripts/csp-header.mjs from the built output. Do not edit by hand.\n` +
    `add_header Content-Security-Policy "${policy}" always;\n`
);
